### PR TITLE
Add new lock icons

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Adding new locked/unlocked icons to uplift

**Related github/jira issue (required)**:
n/a

**Steps necessary to review your pull request (required)**:
- pull branch
- `npm run build:icons`
- make sure new locked, unlocked icons are exported

### CODE REVIEW

**Comment by jmacaluso711** [comment]
@tmcconechy -- updating the soho versions also. only difference is the keyhole

**Comment by tmcconechy** [comment]
OK, pushing this in. We will need a design release added but that should happen sometime this sprint later anyways so wont do it right now.

**Comment by jmacaluso711** [comment]
Getting confirmation that these are final

**Comment by jmacaluso711** [comment]
@tmcconechy confirmed these are good to merge in

**Pull request merged**
