### PR TITLE
Updated ids-icons-standard.sketch

### LINKED ISSUE #314: Tree folder Icons are irregular sizes
After recent icon changes the open and closed folder icon in the tree is showing up as the wrong size (clsoed is too small, open is too big). @nickwynja mentioned in the sketch file its off by one pixel, perhaps causing this.

See result in the tree component: http://master-enterprise.demo.design.infor.com/components/tree/example-index.html

Should these icons by 14x14 or 15x15 in the css to reflect the correct design size?

screen shot 2019-02-25 at 12 27 59 pm

### PR DESCRIPTION
**Pull request by kayiuho**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
- moved open-folder icon to the tree page
- resized all artboards in the tree page to be 14x14

**Related github/jira issue (required)**:
Closes #314 

**Steps necessary to review your pull request (required)**:

### CODE REVIEW

**Comment by nickwynja** [comment]
I ran this build locally and want to show a couple options. @kayiuho, please decide which you think we should go with.

Your PR, as is:

14in14

Alternate: Some icons don't fill the whole artboard and have 1px or sometimes a half pixel of spacing around it. In this example, the folders are 12x12 withing the 14x14 artboard. They may be too small or just right.

12in14

**Comment by kayiuho** [comment]
Visually speaking, I think the alternative (bottom screenshot) looks better. Does that mean we'll have to change the actual icon sizes in the Sketch file?

**Comment by nickwynja** [comment]
@kayiuho Yes, that's correct. In the above example, I just dragged the icon sizes to be 12x12 and then centered them.

**Comment by kayiuho** [comment]
Got cha. I'll get the folders to be 12px wide so they'll "fit" better visually.

**Comment by clepore** [comment]
@nickwynja is this good now?

**Pull request merged**
