### PR TITLE
Adding Native Mobile App Icons Splash Sketch Template

### PR DESCRIPTION
**Pull request by kayiuho**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Adding native mobile app icons splash sketch template.

**Related github/jira issue (required)**:
n/a

**Steps necessary to review your pull request (required)**:
n/a

### CODE REVIEW

**Comment by clepore** [comment]
Should this be in one of the theme folders since we are organizing all assets into themes?

**Comment by kayiuho** [comment]
Since this is not tied to themes, we talked about opening a new directory called `native-mobile` where the design sketch templates would live.

**Comment by clepore** [comment]
Hmm, okay. This might require some thought behind how we organize this folder then.  We might need to do something like this:
```
sketch/
    web/
    mobile/
        ios/
        android/

**Comment by nickwynja** [comment]
I think this still needs more work. I'm going to close this PR and upload the sketch file onto the original ticket and we'll keep the work going there until this is done.

**Pull request closed without merging**
